// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/category": {
            "get": {
                "description": "后端返回现有特型卡类型之接口",
                "produces": [
                    "application/json"
                ],
                "summary": "取得现有特型卡类型",
                "responses": {
                    "200": {
                        "description": "{\"data\": data}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/data": {
            "get": {
                "description": "后端返回数据之接口",
                "produces": [
                    "multipart/form-data"
                ],
                "summary": "取得数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "特型卡名称 (如: car, poem 等)",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "filename",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "XML 文件",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "后端接收 XML 数据之接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "发送 XML 数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "特型卡名称 (如: car, poem 等)",
                        "name": "resource",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "操作类型 (insert, delete)",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "数据内容",
                        "name": "data",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "filename",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "文件形式上传之数据",
                        "name": "file",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/dataname": {
            "get": {
                "description": "后端返回数据文件名之接口",
                "produces": [
                    "application/json"
                ],
                "summary": "取得数据文件名",
                "parameters": [
                    {
                        "type": "string",
                        "description": "特型卡名称 (如: car, poem 等)",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "文件名",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/item": {
            "get": {
                "description": "后端返回某一条数据之接口",
                "produces": [
                    "application/json"
                ],
                "summary": "取得单一数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "特型卡名称 (如: car, poem 等)",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "索引值 (默认为 item.key)",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": data}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/key": {
            "get": {
                "description": "后端返回某一数据类型键值之接口",
                "produces": [
                    "application/json"
                ],
                "summary": "取得数据键值",
                "parameters": [
                    {
                        "type": "string",
                        "description": "特型卡名称 (如: car, poem 等)",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": data}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "后端密码接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "密码较验接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"password\": \"pwd\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pattern": {
            "get": {
                "description": "后端返回配置文件之接口",
                "produces": [
                    "application/json"
                ],
                "summary": "取得配置文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "特型卡名称 (如: car, poem 等)",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "下载信息类型 (intent, garbage, pattern)",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": data}",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "后端接收配置文件之接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "发送配置文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "上传信息类型 (intent, garbage, pattern)",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "特型卡名称 (如: car, poem 等)",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "数据内容",
                        "name": "data",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "操作类型 (insert, delete)",
                        "name": "operation",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"successful!\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/search": {
            "post": {
                "description": "后端搜索系统接口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "搜索系统接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "要搜索的句子",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/setting": {
            "get": {
                "description": "后端返回写入行为描述之接口",
                "produces": [
                    "application/json"
                ],
                "summary": "取得写入行为描述",
                "parameters": [
                    {
                        "type": "string",
                        "description": "特型卡名称 (如: car, poem 等)",
                        "name": "resource",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": data}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "后端接收写入行为描述之接口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "发送写入行为描述",
                "parameters": [
                    {
                        "type": "string",
                        "description": "特型卡名称 (如: car, poem 等)",
                        "name": "resource",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件形式上传之数据",
                        "name": "file",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "数据内容 (JSON 格式)",
                        "name": "data",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://Backend-DianasDog.app.secoder.net",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "特型卡片搜索系统",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
