basePath: /
host: localhost:80
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: 特型卡片搜索系统
  version: "1.0"
paths:
  /data:
    post:
      consumes:
      - multipart/form-data
      description: 后端接收 XML 数据之接口
      parameters:
      - description: '特型卡名称 (如: car, poem 等)'
        in: formData
        name: resource
        required: true
        type: string
      - description: 操作类型 (insert, delete)
        in: formData
        name: type
        required: true
        type: string
      - description: 文件形式上传之数据
        in: formData
        name: file
        type: file
      - description: 数据内容
        in: formData
        name: data
        type: string
      - description: 文件名
        in: formData
        name: filename
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: 'Error: Bad Request'
          schema:
            type: string
      summary: 接收 XML 数据
  /login:
    post:
      consumes:
      - application/json
      description: 后端密码接口
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"password": "pwd"}'
          schema:
            type: string
        "400":
          description: 'Error: Bad Request'
          schema:
            type: string
      summary: 密码较验接口
  /pattern:
    post:
      consumes:
      - multipart/form-data
      description: 后端接收配置文件之接口
      parameters:
      - description: 上传信息类型 (intent, garbage, pattern)
        in: query
        name: type
        required: true
        type: string
      - description: '特型卡名称 (如: car, poem 等)'
        in: query
        name: resource
        required: true
        type: string
      - description: 数据内容
        in: query
        items:
          type: string
        name: data
        required: true
        type: array
      - description: 操作类型 (insert, delete)
        in: query
        name: operation
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "successful!"}'
          schema:
            type: string
        "400":
          description: 错误原因
          schema:
            type: string
      summary: 接收配置文件
  /search:
    post:
      consumes:
      - application/json
      description: 后端搜索系统接口
      parameters:
      - description: 要搜索的句子
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: 'Error: Bad Request'
          schema:
            type: string
      summary: 搜索系统接口
  /setting:
    post:
      consumes:
      - multipart/form-data
      description: 后端接收写入行为之接口
      parameters:
      - description: '特型卡名称 (如: car, poem 等)'
        in: formData
        name: resource
        required: true
        type: string
      - description: 文件形式上传之数据
        in: formData
        name: file
        type: file
      - description: 数据内容 (JSON 格式)
        in: formData
        name: data
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: 'Error: Bad Request'
          schema:
            type: string
      summary: 接收写入行为数据
swagger: "2.0"
